### ISSUE TITLE
Member Editor

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-AetheriusBadgeFilter#2]
A simple interface that allows to easily add or remove badges from guild members without editing the note by hand.

**Comment by Rotscha** [comment]
I thought about modifying the context menu when you rightcklick a member on the guild roster. Add a new menu entry called "Badges" and when you mouseover it, it opens another menu where you select/deselect available badges for that member

**Comment by sirinsidiator** [comment]
I had similar thoughts, but I think it might better to just add new controls to the note editor so the player can see and adjust the generated text if required.
